version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: weatherapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: weatherdb
    ports:
      - "5433:5432"